#!/usr/bin/env bash

# Check if the first argument ($1) is "up" OR "down"
if [[ $1 == "up" || $1 == "down" ]]; then
  if [ $1 == "up" ]; then
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
  else
    wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
  fi
else 
  get_volume() {
    MUTED=$(pamixer --get-mute)
    if [ $MUTED == "true" ]; then
      echo "󰝟"
      return
    fi
    pamixer --get-volume-human
  }

  get_volume
  pactl subscribe \
  | grep --line-buffered "Event 'change' on sink " \
  | while read -r evt; 
  do get_volume | cut -d " " -f1;
  done
fi

