#!/usr/bin/env bash

FIFO="/tmp/playerctl_events_$$"

# Create the FIFO
mkfifo "$FIFO"

cleanup() {
  echo "Cleaning up..."
  rm -f "$FIFO"
  if [ -n "$PLAYERCTL_METADATA_PID" ] && kill -0 "$PLAYERCTL_METADATA_PID" 2>/dev/null; then
      kill "$PLAYERCTL_METADATA_PID" 2>/dev/null
  fi
   if [ -n "$PLAYERCTL_STATUS_PID" ] && kill -0 "$PLAYERCTL_STATUS_PID" 2>/dev/null; then
      kill "$PLAYERCTL_STATUS_PID" 2>/dev/null
  fi
}

# Set trap to run cleanup function on EXIT, SIGHUP, SIGINT, SIGTERM
trap cleanup EXIT HUP INT TERM

get_player_info() {
  PLAYER=$(playerctl -l 2>/dev/null | head -n1)

  if [ -z "$PLAYER" ]; then
    jq -Mcn --arg status "Stopped" \
          --arg player "" \
          --arg artist "Unknown" \
          --arg title "Unknown" \
          --arg album "Unknown" \
          --arg artUrl "" \
          '{status: $status, player: $player, artist: $artist, title: $title, album: $album, artUrl: $artUrl}'
    return # Exit the function
  fi

  if playerctl -p "$PLAYER" status &>/dev/null; then
      STATUS=$(playerctl -p "$PLAYER" status 2>/dev/null || echo "Stopped")
      ARTIST=$(playerctl -p "$PLAYER" metadata artist 2>/dev/null || echo "Unknown")
      TITLE=$(playerctl -p "$PLAYER" metadata title 2>/dev/null || echo "Unknown")
      ALBUM=$(playerctl -p "$PLAYER" metadata album 2>/dev/null || echo "Unknown")
      ALBUMART=$(playerctl -p "$PLAYER" metadata mpris:artUrl 2>/dev/null || echo "")
  else
      STATUS="Stopped"
      ARTIST="Unknown"
      TITLE="Unknown"
      ALBUM="Unknown"
      ALBUMART=""
      PLAYER=""
  fi

  # Return JSON formatted output
  jq -Mcn --arg status "$STATUS" \
        --arg player "$PLAYER" \
        --arg artist "$ARTIST" \
        --arg title "$TITLE" \
        --arg album "$ALBUM" \
        --arg artUrl "$ALBUMART" \
        '{status: $status, player: $player, artist: $artist, title: $title, album: $album, artUrl: $artUrl}'
}

get_player_info

playerctl --follow metadata 2>/dev/null > "$FIFO" &
PLAYERCTL_METADATA_PID=$! # Store the PID of the metadata process
playerctl --follow status 2>/dev/null > "$FIFO" &
PLAYERCTL_STATUS_PID=$!   # Store the PID of the status process

while read -r _; do
  while read -r -t 0.05 additional_line < "$FIFO"; do
    # Do nothing, just consume the line
    :
  done
  get_player_info
done < "$FIFO" 

